test(client): cover typedSql + queryCompiler + @prisma/adapter-libsql (#27801)
This PR:
- contributes to
[ORM-1073](https://linear.app/prisma-company/issue/ORM-1073/verify-or-fix-esm-support-for-typedsql)
- showcases an e2e test where `typedSql` fails when paired with
`queryCompiler` and `@prisma/adapter-better-sqlite3`
- the test is mostly copied from
https://github.com/prisma/prisma-examples/pull/8258

The error log is:

```
prisma:driver-adapter:better-sqlite3 [js::queryRaw] '{\n' +
  '  "sql": "SELECT te.\\"id\\", te.\\"type\\", te.\\"variant\\"\\nFROM \\"TrackingEvent\\" te\\nWHERE\\n($1 IS NULL OR te.\\"type\\" IN (SELECT value FROM json_each($1)))\\nAND ($2 IS NULL OR te.\\"variant\\" IN (SELECT value FROM json_each($2)))",\n' +
  '  "args": [\n' +
  '    "[\\"PageOpened\\",\\"ButtonClicked\\"]",\n' +
  '    "[\\"BlueBuyButton\\",\\"RedBuyButton\\"]"\n' +
  '  ],\n' +
  '  "argTypes": [\n' +
  '    "Text",\n' +
  '    "Text"\n' +
  '  ]\n' +
  '}' +7ms
prisma:driver-adapter:better-sqlite3 Error in performIO: '{}' +0ms
<path>/generator-prisma-client/basic-typedsql-query-compiler/node_modules/.pnpm/@prisma+adapter-better-sqlite3@6.13.0/node_modules/@prisma/adapter-better-sqlite3/dist/index.js:519
      const stmt = this.client.prepare(query.sql).bind(mapQueryArgs(query.args, query.argTypes));
                                                  ^

RangeError: Too many parameter values were provided
```

---------

Co-authored-by: jkomyno <12381818+jkomyno@users.noreply.github.com>
Co-authored-by: Jacek Malec <malec@prisma.io>