add required unique on 1 to 1 relation and update snapshot
Error was
     Get DMMF: Schema parsing
    error: Error parsing attribute "@relation": A one-to-one relation must use unique fields on the defining side. Either add a unique constraint, or change the relation to one-to-many.
      -->  schema.prisma:16
       |
    15 |   companyId Int
    16 |   company Company @relation(fields: companyId, references: id)
    17 | }
       |