chore: use swc instead of ts-jest for some packages
and CLI fixing studio error "Error: Cannot find module '@prisma/sdk'" when executing `src/bin.ts`
See https://github.com/pnpm/pnpm/issues/2174