chore(deps): update engines to 3.16.0-5.f9559ae69c68d71b1787de8a4f2d4fda1a612eba (#13714)
* chore(deps): update engines to 3.16.0-5.f9559ae69c68d71b1787de8a4f2d4fda1a612eba

* fix: add @unique on defining side of relation

* more

* so much more

* add required unique on 1 to 1 relation and update snapshot

Error was
     Get DMMF: Schema parsing
    error: Error parsing attribute "@relation": A one-to-one relation must use unique fields on the defining side. Either add a unique constraint, or change the relation to one-to-many.
      -->  schema.prisma:16
       |
    15 |   companyId Int
    16 |   company Company @relation(fields: companyId, references: id)
    17 | }
       |

Co-authored-by: Jan Piotrowski <piotrowski+github@gmail.com>
Co-authored-by: Joël Galeran <Jolg42@users.noreply.github.com>