revert to private platform?: Platform | string
because that exploded in https://github.com/prisma/prisma/actions/runs/6669272870/job/18126674298?pr=20165#step:4:131

```
Error: packages/client build: src/runtime/core/engines/binary/BinaryEngine.ts(174,81): error TS2345: Argument of type 'String | Platform' is not assignable to parameter of type 'PathLike'.
packages/client build:   Type 'String' is not assignable to type 'PathLike'.
packages/client build:     Type 'String' is missing the following properties from type 'Buffer': write, toJSON, equals, compare, and 95 more.
Error: packages/client build: src/runtime/core/engines/binary/BinaryEngine.ts(176,68): error TS2769: No overload matches this call.
packages/client build:   Overload 1 of 3, '(input: null): null', gave the following error.
packages/client build:     Argument of type 'String | Platform' is not assignable to parameter of type 'null'.
packages/client build:       Type 'String' is not assignable to type 'null'.
packages/client build:   Overload 2 of 3, '(input: string | number | boolean): string', gave the following error.
packages/client build:     Argument of type 'String | Platform' is not assignable to parameter of type 'string | number | boolean'.
packages/client build:       Type 'String' is not assignable to type 'string | number | boolean'.
packages/client build:   Overload 3 of 3, '(input: void | undefined): undefined', gave the following error.
packages/client build:     Argument of type 'String | Platform' is not assignable to parameter of type 'void | undefined'.
packages/client build:       Type 'String' is not assignable to type 'void'.
Error: packages/client build: src/runtime/core/engines/binary/BinaryEngine.ts(869,7): error TS2322: Type 'String | Platform | undefined' is not assignable to type 'string | undefined'.
packages/client build:   Type 'String' is not assignable to type 'string'.
packages/client build:     'string' is a primitive, but 'String' is a wrapper object. Prefer using 'string' when possible.
```