Ignore type check for GlobbyOptions
ts-node ../../src/bin.ts up
../../src/Lift.ts:715:9 - error TS2345: Argument of type '{ cwd: string; }' is not assignable to parameter of type 'GlobbyOptions'.
  Object literal may only specify known properties, and 'cwd' does not exist in type 'GlobbyOptions'.